# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [2]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Reverse a vector (first element becomes last) 

In [3]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [4]:
b=np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [5]:
c=np.array([1,2,0,0,4,0])
c.nonzero()

(array([0, 1, 4], dtype=int32),)

#### 6. Create a 3x3 identity matrix 

In [6]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values 

In [7]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.71474917 0.32517142 0.18631074]
  [0.02836472 0.69632801 0.21190386]
  [0.53288407 0.44596976 0.20818278]]

 [[0.85589104 0.34992129 0.6942395 ]
  [0.17869951 0.56268627 0.41697635]
  [0.22737752 0.89094859 0.32163245]]

 [[0.88718952 0.02686473 0.62868183]
  [0.21530348 0.17744395 0.07135106]
  [0.21640096 0.48809443 0.1273058 ]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [8]:
x=np.random.random((10,10))
print(x.min(),x.max())

0.0027617229530716436 0.997490624523905


#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [9]:
x=np.array([[0,1],[1,0]])
np.tile(x,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [10]:
a=np.arange(15).reshape(5,3)
b=np.arange(6).reshape(3,2)
np.dot(a,b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


In [11]:
x=np.array([0, 1, 2, 3, 4])
np.tile(x,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [12]:
a = np.arange(5)
b=np.zeros((5,1))
a+b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 13. Create a random vector of size 10 and sort it 

In [13]:
x=np.random.random(10)
x.sort()
print(x)

[0.02820778 0.27598765 0.29679004 0.38256316 0.42855584 0.53477566
 0.56529589 0.67556694 0.89838485 0.94430071]


#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [14]:
x=np.random.rand(5,10)
x.mean(axis=1)

array([0.54925177, 0.36830459, 0.35841098, 0.5964973 , 0.47135454])

#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [15]:
from numpy import newaxis
a=np.arange(1,11)
a[:,newaxis]*a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [16]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.04063791, 1.37420366, 1.02560328, 1.27910871, 1.92658395])

#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [17]:
x=np.array([1,2,3,4,5])
x0=np.zeros(5+((len(x)-1))*3)
for i in range(5):
    x0[i*4]=x[i]
print(x0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [18]:
x=np.arange(25).reshape(5,5)
x[[0,1]]=x[[1,0]]
print(x)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [19]:
Z = np.random.randint(0,10,50)
np.argmax(np.bincount(Z))

5

#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [20]:
Z = np.arange(10000)
n=3
np.random.shuffle(Z) 
print (Z[np.argsort(Z)[-n:]])

[9997 9998 9999]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [21]:
original_array=np.random.randint(0,2,(20,3))
unique_rows = np.unique(original_array, axis=0)
print(unique_rows)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [24]:
def moving_avg(arr,n):
    avg_list=[]
    for i in range(0,(len(arr)-n+1)):
        part_avg=sum(arr[i:(i+n)])/float(n)
        avg_list+=[part_avg]
    print(avg_list)
##test
array=[1,3,7,14,18,23,41]
size_sw=4
moving_avg(array,size_sw)

[6.25, 10.5, 15.5, 24.0]


#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [35]:
x = np.random.uniform(0,1,(4,4))
print(x)
arridx=np.nonzero(x>0.5)
print(*zip(arridx[0],arridx[1]))

[[0.38276577 0.64182499 0.76215875 0.12640509]
 [0.93203643 0.41375887 0.72799155 0.72310173]
 [0.38780327 0.65598808 0.11684716 0.43787637]
 [0.9615937  0.61823623 0.06935173 0.53870476]]
(0, 1) (0, 2) (1, 0) (1, 2) (1, 3) (2, 1) (3, 0) (3, 1) (3, 3)


#### 25. Write a function returning distance between two points

In [42]:
import math
def distance(p1,p2):
    result=math.sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2)
    return result

In [43]:
##test
p1=(1,3)
p2=(4,8)
print(distance(p1,p2))

5.830951894845301
